language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: pSWvZGpyJ+7ZQICn35gWvEZN8FW7XN7tvsHwNpMTA6oyI9f2Rv706Ep+z6I7E32em5O6Iix1JtM5X1xFOHabIWCxz6ASNzZ3wu08okXGUVAWvLyrcNhpPuUC3cGHxb0iTKbE8FNRiSirXrMhdCBN41xuQWHJ2YNcY1iOKkYFuYjbV294YlfhzsZWTlkdVZ76DX4dsMJAHibNC929oHhYOHUrOu9PWTmgLZX4aCNaRfx/MsbSNInuQ4+PZagnKK76d+EOz6Pyjb+Ruj2+x2qxtMHSVzBmrhQgakKcBf2lXnQkAI1HsSLlJKQEgFGtEw1QQHeql5asnMwF8U7UA+0haYGOvIEbM0BRHYqTXlz9C5QC1mTHC1b70B4S8DgyBiqmDvPaUv0fJ3e2esMyKyMhAT9yS4Y7C4Qy2D0UGenRGRcnJ0HVP6LKjjmsmfVZzRoxyZdLzEttzClPJo31KyoZA9Wd0AMqXQel1uogIWvrKqKYGSSasY76ji/myLgZueMGNXERK+falGJuZVxGqMk9br7fAX9dXcSUAv6fFe09khv4Yw+2tq+Uury+ne1lOjYp22HCxqnZ+X/L1Lc2CjfLYHoM5xdCH8fPeIuVn+uVAihPsUFiuZbephYmgEhOjcQIi7VnQ+kprYWQWxuPbetbrWPtclRG3MQjjMFi18zOyYI=
  file:
    - 'is-hidden.js'
    - 'is-hidden.min.js'
  on:
    tags: true
