language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: LeeGf3FG8VBq6JlT/cpePlufDrwqTLPIJcQnHVX13xgewmEvoKjbj37QdavtoGdbcoJ9/T7GGyuQI2nQaNHYubvlBRJyWkgj2N7vzgvOr1fJnWof49GJPeNJSTKCiVWJ+butDGDvSPXqwEzwLJJGbnYGZqmDUmUcMKpVD3Id+ajRf5jki057Bqarosfq73bdvuTc9es97PVAKvf99HqXPGKJ3n4XtKjqo0qJyBKuDH0RHsoOMin09B8ZACKFyr6B4n4IbXms5ESKIbstePs7dEB01c6pfpo0FtieruEfevHRhTCK/aeEbCN2xMbQs+WQjVcAqNRudvpaE2eT5lYukNAgxQdbPpT5mZuZquRtaZbVZAIC1+Zz3177abfIF5uKUyCMi3lt9+PrV1svEUaNXuhT0OtLP4yJR/sD94KVJk3Sksu/KFbUdK+MXhnoOCKnoQyai6qrBW9kIZ/pXUxBfuNbgHrdGgGSy4kijPhfHM3hPLxUg7bCtC+c3RaeZRob7y7kgOEzo4kZ5LPRfQSEsAnhWTBLn/qoma+aiWAjjf6dGH/jHNtXES6HZI5ZqBD2cm1oLVU9jNn7OevhjhBfLz86X01113OaWLjRNFt+znC0qAH7wY3AAnBWte7AZJJuAOWIPEA2z1Y0gvobcSHz8yn1253iSc7Bry/FZCXi3aU=
  file:
    - "is-hidden.js"
    - "is-hidden.min.js"
  on:
    tags: true
